### ISSUE TITLE
Sudden date blocking on WordPress plugin despite availability elsewhere

### ISSUE THREAD

**Issue by vitaliyhayda** [Hostaway/wordpress-plugin#18]
For the past two years, everything has been functioning smoothly. However, in the last 12 hours or so, all of our dates have become unexpectedly blocked on WordPress, even though they remain available on other platforms. We have not made any changes, and our WordPress settings are configured to prevent automatic updates.

Please provide guidance on this pressing issue. We have already received 4 emails from concerned customers.

**Comment by kaitfast** [comment]
We are also seeing this issue on our site. Any updates??

**Comment by vitaliyhayda** [comment]
Customer support has resolved the issue, and it is now working for me. Therefore, I will be closing this issue on GitHub.
